routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
  //  return view('layouts.appCliente');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//rutas para cliente o visitante
Route::get('/', 'GuestController@index')->name('inicio');
Route::get('/catalogo', 'GuestController@catalogo')->name('catalogo');
Route::get('/autores', 'GuestController@autores')->name('autores');
Route::get('/info', 'GuestController@info')->name('info');
Route::get('/carrito', 'GuestController@carrito')->name('carrito');

//rutas para administrador
Route::resource('/panel', 'PanelController');

//rutas para los libros
Route::resource('/libro', 'LibrosController');

 Route::post('/registrar', 'LibrosController@registrar');
 Route::post('/buscar', 'LibrosController@buscar');
 Route::post('/eliminar', 'LibrosController@destroy');
 Route::post('/editar', 'LibrosController@editar');
 Route::get('apartar/{id_libro}', 'LibrosController@apartar');
 Route::post('/ver','LibrosController@ver');
 Route::get('eliminar_apartado/{id_apartado}', 'LibrosController@eliminar_apartado');



//rutas para los prestamos
Route::resource('/prestamo', 'PrestamoController');
Route::get('/prestamo/Resumen', 'PrestamoController@index')->name('resumen');
Route::get('/prestamo/Crear', 'PrestamoController@create')->name('crear');
Route::get('/prestamo/verifica', 'PrestamoController@verifica')->name('verifica');
Route::get('/prestamo/Editar', 'PrestamoController@edit')->name('editar');
Route::get('/prestamo/Entregar', 'PrestamoController@entregar')->name('entregar');
Route::get('/prestamo/Ver-Prestamos', 'PrestamoController@show')->name('mostrar');
Route::post('/buscarPrestamo', 'PrestamoController@buscarPrestamo');
Route::post('/editarPrestamo', 'PrestamoController@editarPrestamo');
Route::post('/verificarUsuario', 'PrestamoController@buscarUsuario');
Route::get('/entregado', 'PrestamoController@entregar');
Route::get('/prestamo/{id}/entregar', 'PrestamoController@entregar');


//rutas para los pedido
Route::resource('/pedido', 'PedidoController');
Route::post('/registrarr', 'PedidoController@registrar');

//rutas para los usuarios
Route::resource('/usuario', 'UsersController');
Route::get('/perfil','UsersController@perfil');

//rutas para los inventario
Route::resource('/inventario', 'InventarioController');

//rutas para los estadisticas
Route::resource('/estadisticas', 'EstadisticsController');

app/prestamo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prestamo extends Model
{
    protected $fillable = [
        'isbn', 'nombre_material','nombre_alumno', 'no_control',
         'estado', 'fecha_prestamo', 'fecha_entrega',
    ];
    
}

app/Http/Controllers/PrestamoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\prestamo;
use App\libro;
use App\cliente;
use Carbon\Carbon;
use App\User;
class PrestamoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
      public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        //$fecha = new DateTime();
        //echo $fecha->format('Y-m-d H:i:s');
        //$libros = libro::All();
        //$clientes = cliente::All();
        $prestamo = prestamo::orderBy('id', 'ASC')->where('estado', 'PRESTADO')->paginate(4);
        //->where('fecha_entrega', '$fecha')->paginate();
        //return view('admin.prestamo.index');// compact('prestamos', 'libros','clientes'));
        //$prestamo= prestamo::All();
        return view('admin.prestamo.index', compact('prestamo'));
    }

    public function verifica(){
        
        return view('admin.prestamo.verifica');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.prestamo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,['isbn'=> 'required', 'nombre_material'=> 'required', 
        'nombre_alumno'=>'required','no_control'=>'required','estado'=> 'required',
         'fecha_prestamo'=> 'required', 'fecha_entrega'=> 'required']);
        $prestamo  = prestamo::create($request->all());
        return redirect()->route('prestamo.create', $prestamo->id)
        ->with('info','Prestamo registrado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User::orderBy('id', 'ASC')->where('name', '')->paginate(1);

        return view('admin.prestamo.show', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $prestamo = prestamo::find($id);
        return view('admin.prestamo.edit', compact('prestamo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $prestamo = prestamo::find($id);
        $prestamo->isbn = $request->get('isbn');
        $prestamo->nombre_material = $request->get('nombre_material');
        $prestamo->nombre_alumno = $request->get('nombre_alumno');
        $prestamo->no_control = $request->get('no_control');
        $prestamo->estado = $request->get('estado');
        $prestamo->fecha_prestamo = $request->get('fecha_prestamo');
        $prestamo->fecha_entrega = $request->get('fecha_entrega');
        $prestamo->save();
        return redirect()->route('prestamo.index', $prestamo->id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function buscarPrestamo(Request $request){

        $busqueda =$request->input('search');
        $prestamo = new prestamo();
            $prestamo = prestamo::where('no_control', $busqueda)->get();
            return view('admin.prestamo.index', compact('prestamo'));
     
    }

    public function buscarUsuario(Request $request){

        $busqueda =$request->input('search');
        $users = new user();
            $users = user::where('nocontrol', $busqueda)->get();
            return view('admin.prestamo.show', compact('users'));
     
    }
    public function entregar(Request $request,$id){
        $prestamo = prestamo::find($id);
        DB::table('prestamos')
            ->where('id', $id)
            ->update(['estado' => 'ENTREGADO']);
            
        return redirect()->route('prestamo.index', $prestamo->id);
     
    }
}

resources/views/admin/prestamo/create.blade.php
@extends('layouts.app')

@section('title')
Crear Prestamo
@endsection
    
@section('content')
<br/> <br/>

<div class="container"   >
<div class="row justify-content-center" >
  <div class="col-md-6" >
    <div class="card" style="padding:45px">
    
  <form method="POST" action="{{ route('prestamo.store') }}">
     @csrf
    <div class="form-group">
        <label for="formGroupExampleInput2">Código del material</label>
        <input type="text" class="form-control" id="codigoMaterial"
        placeholder="1235" name="isbn">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Título del material</label>
        <input type="text" class="form-control" id="titulo"
        placeholder="Titulo" name="nombre_material">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">Nombre del usuario</label>
        <input type="text" class="form-control" id="nombreUser"
        placeholder="Nombre Apellido" name="nombre_alumno">
    </div>
    <div class="form-group">
        <label for="formGroupExampleInput2">No. de Control</label>
        <input type="text" class="form-control" id="nocontrol"
        placeholder="12131415" name="no_control">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="formGroupExampleInput2"
         name="estado" value="PRESTADO">
    </div>
    <h7>Fecha de prestamo</h7>
    <?php $fcha = date("Y-m-d");?>
    <input type="date" class="form-control"  value="<?php echo $fcha;?>" name="fecha_prestamo">
    <h7>Fecha de entrega</h7>
    <?php $fcha = date("Y-m-d");?>
    <input type="date" class="form-control"  value="<?php echo $fcha;?>" name="fecha_entrega" id="fecha_entrega">

    <center>

        <button id= "btnImprimir" onclick="setDoc()" type="" class="btn btn-primary" style="margin: 10px">
                {{ __('Imprimir') }}
    </button>
    <button id= "btnRegistrar" type="submit" class="btn btn-primary" style="margin: 10px">
                {{ __('Registrar') }}
    </button>
    </center>
      </form>
    <input type="hidden" value="{{ Auth::user()->name  }}" id="nombrebiblio" name="nombreBiblio" />



      
  </div>
  </div>
</div>
</div>

<script>
document.getElementById('btnRegistrar').disabled = true;
</script>

@endsection

resources/views/admin/prestamo/edit.blade.php
@extends('layouts.app')

@section('title')
Crear Prestamo
@endsection
    
@section('content')

<div class="container"   >
<div class="row justify-content-center" >
  <div class="col-md-6" >
    <div class="card" style="padding:45px">
  <form method="POST" action="{{  route('prestamo.update', $prestamo->id) }}">
  {{ method_field('put') }}
            {{ csrf_field() }}
            <div class="form-group">
        <label for="formGroupExampleInput2">Código del material</label>
        <input type="text" class="form-control" id="formGroupExampleInput2"
         name="isbn" value="{{$prestamo->isbn}}">
    </div>
     <div class="form-group">
      <label for="formGroupExampleInput2">Título del material</label>
      <input type="text" class="form-control" id="formGroupExampleInput2"
      placeholder="Titulo" name="nombre_material" value="{{$prestamo->nombre_material}}">
      </div>
      <div class="form-group">
          <label for="formGroupExampleInput2">Nombre del usuario</label>
          <input type="text" class="form-control" id="formGroupExampleInput2"
          placeholder="Nombre Apellido" name="nombre_alumno" value="{{$prestamo->nombre_alumno}}">
      </div>
      <div class="form-group">
          <label for="formGroupExampleInput2">No. de Control</label>
          <input type="text" class="form-control" id="formGroupExampleInput2"
          placeholder="12131415" name="no_control" value="{{$prestamo->no_control}}">
      </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Estado del Prestamo</label>
    <select class="form-control" id="exampleFormControlSelect1" name="estado" required>
      <option value="PRESTADO" >PRESTADO</option>
      <option  vaelu= "ENTREGADO">ENTREGADO</option>
    </select>
  </div>
      <h7>Fecha de prestamo</h7>
      <?php $fcha = date("Y-m-d");?>
      <input type="date" class="form-control"  value="{{$prestamo->fecha_prestamo}}" name="fecha_prestamo">
      <h7>Fecha de entrega</h7>
      <?php $fcha = date("Y-m-d");?>
      <input type="date" class="form-control"  value="{{$prestamo->fecha_entrega}}" name="fecha_entrega">

    <center>
    <button type="submit" class="btn btn-primary" style="margin: 10px">
                {{ __('Registrar') }}
    </button>
    </center>
      </form>
  </div>
  </div>
</div>
</div>

@endsection

resources/views/admin/prestamo/index.blade.php
@extends('layouts.app')

@section('title')
Prestamos
@endsection
    
@section('content')

<br/><br/><br/>
<div class="col m12 "> 
<form action="{{ action('PrestamoController@buscarPrestamo') }}" method="post">
@csrf
            <div class="row">
            <div class="col m6">
             
                 <div class="" style="margin-top:8%;">
                        <div class="nav-wrapper  blue lighten-5" style="background-color:; border-radius:8px;">
                              <form>
                                <div class="input-field">
                                  <input id="search" type="search" name="search" required>
                                  <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                                  <i class="material-icons">close</i>
                                </div>
                              </form>
                            </div>     
                    </div>
                    
                    </div>
                    <div class="col m2" style="margin-top:3%;">
                    <button class="btn waves-effect waves-light"  style=" border-radius:15px;"type="submit" name="action">Buscar
                <i class="material-icons right">search</i>
              </button></div>
              </form> 

    <table class="card" style="margin-top: 5%" >
                    <thead style="background: #FFFFFF">
                        <tr>
                            <th>Codigo</th>
                            <th>Titulo</th>
                            <th>Usuario</th>
                            <th>No. Control</th>
                            <th>Estado</th>
                            <th>Fecha de préstamo</th>
                            <th>Fecha de entrega</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                
                    <tbody style="background: #FFFFFF">
                    @foreach($prestamo as $prestamoL)
                        <tr>
                            <td>{{$prestamoL->isbn}}</td>
                            <td>{{$prestamoL->nombre_material}}</td>
                            <td>{{$prestamoL->nombre_alumno}}</td>
                            <td>{{$prestamoL->no_control}}</td>
                            <td>{{$prestamoL->estado}}</td>
                            <td>{{$prestamoL->fecha_prestamo}}</td>
                            <td>{{$prestamoL->fecha_entrega}}</td>
                            <td>
                             <a class="waves-effect waves-light btn-small" href="{{ route('prestamo.edit', $prestamoL->id )}}"><i class="material-icons">edit</i></a>                             
                            </td>
                        </tr>                    
                    @endforeach
                    </tbody>
        </table>

         


@endsection

resources/views/admin/prestamo/show.blade.php
@extends('layouts.app')

@section('title')
Mostrar Prestamo
@endsection
    
@section('content')

<h3>Buscar usuario</h3>

<br/><br/><br/>
<div class="col m12 "> 
<form action="{{ action('PrestamoController@buscarUsuario') }}" method="post">
@csrf
            <div class="row">
            <div class="col m6">
             
                 <div class="" style="margin-top:8%;">
                 <h5>Inserte número de control</h5>
                        <div class="nav-wrapper  blue lighten-5" style="background-color:; border-radius:8px;">
                              <form>
                                <div class="input-field">
                                  <input id="search" type="search" name="search" required>
                                  <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                                  <i class="material-icons">close</i>
                                </div>
                              </form>
                            </div>     
                    </div>
                    
                    </div>
                    <div class="col m2" style="margin-top:3%;">
                    <button class="btn waves-effect waves-light"  style=" border-radius:15px;"type="submit" name="action">Buscar
                <i class="material-icons right">search</i>
              </button>
              </div>
              

    <table class="card" style="margin-top: 5%" >
                    <thead style="background: #FFFFFF">
                        <tr>
                            <th>Nombre</th>
                            <th>Email</th>
                            <th>No. Control</th>
                        </tr>
                    </thead>
                
                    <tbody style="background: #FFFFFF">
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->nocontrol}}</td>
                        </tr>                    
                    @endforeach
                    </tbody>
        </table>
        </form> 
@endsection

resources/views/admin/prestamo/verifica.blade.php
@extends('layouts.app')

@section('title')
Crear Prestamo
@endsection
    
@section('content')

<h3>Vista para los Verificar un Prestamo</h3>

<div class="container">
    <h3 class="center-align">VERIFICAR</h3>
    <div class="row">
    <!-- Comienzo de la columna que muestra información del usuario-->
        <div class="col s6">
    <!-- Inicia formulario que nos ayudará a mostrar los datos del usuario "jalados" de l BD
    así mismo mostrará si el alumno tiene un adeudo-->
        <h6>Buscar usuario</h6>
            <div class="row">
                <div class="col s7">
                <nav>
                    <form>
                    <div class="nav-wrapper blue"style=" border-radius:8px;" >
                        <div class="input-field" style="border-radius:15px;">
                        <input id="search" type="search" required>
                        <label class="label-icon" for="search"><i class="material-icons">search</i>Inserte N° de control</label>
                        <i class="material-icons">close</i>
                        </div>
                    </form>
                    </div>
                </nav> 
                </div>
                <div class="col s4">
                <a href="" class="btn btn-sm btn" style="background: #3AAF88">Buscar</a>
                </div>
            </div>
            <br/><br/>
            <div class="row">
                <div class="input-field">
                    <i class="material-icons prefix">perm_identity</i>
                    <label for="nombre">Nombre</label>
                    <input type="text" name="nombre" required>
                </div>
                <div class="input-field">
                    <i class="material-icons prefix">person_pin</i>
                    <label for="apellido">Apellidos</label>
                    <input type="text" name="apellidos" required>
                </div>
                <div class="input-field">
                    <i class="material-icons prefix">mode_edit</i>
                    <label for="numControl">Número de control</label>
                    <input type="text" name="numControl" required>
                </div>
                <div class="input-field ">
                    <i class="material-icons prefix">group</i>
                    <select name="tipo_usuario">
                        <option value="" disabled selected>Tipo de usuario</option>
                        <option value="1">Alumno</option>
                        <option value="2">Docente</option>
                        <option value="3">Investigador</option>
                    </select>
                </div>
                <div class="input-field ">
                    <i class="material-icons prefix">school</i>
                    <select name="carrera">
                        <option value="" disabled selected>Carrera</option>
                        <option value="1">Lic. en Administración</option>
                        <option value="2">Ing. en TIC's</option>
                        <option value="3">Ing. Mecatrónica</option>
                    </select>
                </div>
                <br/><br/>
                <h5 align="center">ADEUDOS</h5>
                <table>
                <thead style="background: #3AAF88">
                        <tr>
                            <th>Libro</th>
                            <th>Préstamo</th>
                            <th>Entrega</th>
                        </tr>
                </thead>
                        <tr>
                            <td>Termodinamica 2</td>
                            <td>11/11/2019</td>
                            <td>14/11/2019</td>
                        </tr>
                </table>
            </div>
        </div>
        <!-- Comienzo de la columna que muestra información del libro/revista-->
        <div class="col s6">
        <h6>Buscar libro/revista</h6>
            <div class="row">
            <form>
                    <div class="col s7">
                    <nav>
                    <div class="nav-wrapper blue">
                        <div class="input-field">
                        <input id="search" type="search" required>
                        <label class="label-icon" for="search"><i class="material-icons">search</i>Inserte código</label>
                        <i class="material-icons">close</i>
                        </div>
                    </div>
                </nav> 
                    </div>
                    <div class="col s4">
                    <a href="" class="btn btn-sm btn" style="background: #3AAF88">Buscar</a>
                    </div>
            </form>
            </div>
            <br/><br/>
            <div class="row">
                <div class="input-field">
                    <i class="material-icons prefix">perm_identity</i>
                    <label for="nombre">Autor</label>
                    <input type="text" name="nombre" required>
                </div>
                <div class="input-field">
                    <i class="material-icons prefix">perm_identity</i>
                    <label for="nombre">Titulo</label>
                    <input type="text" name="nombre" required>
                </div>
            </div>        
        </div>
    </div>
    
    <form action="POST" action="">
    
    </form>

</div>

@endsection